const assert=require('assert');
const Access=require('../assets/v9/access-router-engine.js');
const Self=require('../assets/v9/self-enrollment-engine.js');
const White=require('../assets/v9/whitelist-engine.js');
const Roll=require('../assets/v9/rollout-engine.js');
const engines={selfEnrollment:Self,whitelist:White,rollout:Roll};
const ready={verdict:'READY',ready:true},blocked={verdict:'BLOCKED',ready:false};
const identity='device-gateway';
const grant={type:'tcc-v9-self-enroll-grant',identity,issuedAt:'2026-08-31T09:00:00Z',expiresAt:'2026-08-31T10:00:00Z',tokenVersion:'v1'};
const selfConfig={enabled:true,requireReadiness:true,readinessApproved:true,tokenVersion:'v1',expiresAt:'2030-01-01T00:00:00Z',maxGrantMinutes:60};
const whitelist={enabled:false,requireReadiness:true,identities:[],candidatePath:'v9-app/',fallbackPath:'./'};
const rollout={stage:'preview',canaryPercent:0,killSwitch:false,requireReadiness:true,salt:'stable',v8Path:'./',previewPath:'v9-preview/',canaryPath:'v9-app/',productionPath:'v9-app/'};
let d=Access.route({identity,grant,selfConfig,whitelistConfig:whitelist,rolloutConfig:rollout,readiness:ready,now:new Date('2026-08-31T09:30:00Z'),engines});
assert.equal(d.engine,'v9');assert.equal(d.path,'v9-app/');assert.equal(d.source,'self_enroll');
d=Access.route({identity,grant,selfConfig,whitelistConfig:whitelist,rolloutConfig:rollout,readiness:blocked,now:new Date('2026-08-31T09:30:00Z'),engines});
assert.equal(d.engine,'v8');assert.equal(d.reason,'readiness_blocked');
d=Access.route({identity,grant,selfConfig,whitelistConfig:whitelist,rolloutConfig:{...rollout,killSwitch:true},readiness:ready,now:new Date('2026-08-31T09:30:00Z'),engines});
assert.equal(d.engine,'v8');assert.equal(d.reason,'kill_switch');
d=Roll.decide({config:{...rollout,stage:'canary',canaryPercent:100},identity,readiness:ready});
assert.equal(d.engine,'v9');assert.equal(d.path,'v9-app/');
d=Access.route({identity,grant:null,selfConfig:{...selfConfig,enabled:false},whitelistConfig:whitelist,rolloutConfig:rollout,readiness:ready,engines});
assert.equal(d.engine,'v8');
console.log(JSON.stringify({ok:true,module:'tcc-v9-access-gateway',checks:['self-enroll-to-candidate','blocked-readiness-to-v8','kill-switch-to-v8','canary-to-candidate','zero-percent-control']},null,2));