const assert=require('node:assert/strict');
const Engine=require('../assets/v9/device-test-engine.js');
const ready={verdict:'READY',ready:true},blocked={verdict:'BLOCKED',ready:false};
const policy={enabled:true,maxWindowMinutes:60,minimumRuns:10,minimumSuccessfulRuns:10,maxFailureRate:.05,maxRoutingErrors:0,maxSourceErrors:0,maxAverageDurationMs:12000,requireReadiness:true,requireCanaryPercentZero:true,autoCloseOnRollback:true};
const now=new Date('2026-08-31T11:00:00Z'),grant={expiresAt:'2026-08-31T12:00:00Z'};
let r=Engine.evaluate({policy,telemetry:{runs:0},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now});
assert.equal(r.decision,'OBSERVE');assert.equal(r.close,false);
r=Engine.evaluate({policy,telemetry:{runs:10,queryFailures:0,routingErrors:0,sourceErrors:0,avgDurationMs:1000},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now});
assert.equal(r.decision,'PASS');assert.equal(r.close,true);
r=Engine.evaluate({policy,telemetry:{runs:10,queryFailures:1,routingErrors:0,sourceErrors:0,avgDurationMs:1000},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now});
assert.equal(r.decision,'ROLLBACK');assert.ok(r.reasons.includes('failure_rate'));assert.equal(r.close,true);
r=Engine.evaluate({policy,telemetry:{runs:10,queryFailures:0,routingErrors:1,sourceErrors:0,avgDurationMs:1000},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now});assert.equal(r.decision,'ROLLBACK');
r=Engine.evaluate({policy,telemetry:{runs:10,queryFailures:0,routingErrors:0,sourceErrors:1,avgDurationMs:1000},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now});assert.equal(r.decision,'ROLLBACK');
r=Engine.evaluate({policy,telemetry:{runs:10,queryFailures:0,routingErrors:0,sourceErrors:0,avgDurationMs:13000},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now});assert.equal(r.decision,'ROLLBACK');assert.ok(r.reasons.includes('latency'));
r=Engine.evaluate({policy,telemetry:{runs:0},readiness:blocked,rolloutConfig:{canaryPercent:0},grant,now});assert.equal(r.decision,'ROLLBACK');assert.ok(r.reasons.includes('readiness_not_ready'));
r=Engine.evaluate({policy,telemetry:{runs:0},readiness:ready,rolloutConfig:{canaryPercent:1},grant,now});assert.equal(r.decision,'ROLLBACK');assert.ok(r.reasons.includes('random_canary_not_zero'));
r=Engine.evaluate({policy,telemetry:{runs:0},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now:new Date('2026-08-31T12:01:00Z')});assert.equal(r.decision,'CLOSE');assert.equal(r.close,true);
r=Engine.evaluate({policy:{...policy,enabled:false},telemetry:{},readiness:ready,rolloutConfig:{canaryPercent:0},grant,now});assert.equal(r.decision,'CLOSED');assert.equal(r.close,true);
console.log(JSON.stringify({ok:true,module:'tcc-v9-device-test-lifecycle',checks:['observe','pass-closes','failure-rollback','routing-rollback','source-rollback','latency-rollback','readiness-rollback','zero-canary-required','expiry-close','disabled-closed']},null,2));
