const assert=require('node:assert/strict');
const fs=require('node:fs');
const Direct=require('../assets/v9/adapters/direct-offers.js');
const Session=require('../assets/v9/session-engine.js');
const offers=JSON.parse(fs.readFileSync('data/v9/italy-offers.json','utf8'));
const report=JSON.parse(fs.readFileSync('data/v9/italy-build-report.json','utf8'));
const ewivaEmsp=offers.emspOffers.filter(o=>o.provider==='Enel On Your Way'&&o.metadata?.network==='Ewiva');
const ewivaSuper=offers.subscriptionOffers.filter(o=>o.selectionId==='enel_plug_and_go_super'&&o.metadata?.network==='Ewiva');
const ewivaExplorer=offers.subscriptionOffers.filter(o=>o.selectionId==='enel_plug_and_go_explorer'&&o.metadata?.network==='Ewiva');
const n=report.ewivaEnelEmspOffers;
assert.ok(n>1700);
assert.equal(ewivaEmsp.length,n); assert.equal(ewivaSuper.length,n); assert.equal(ewivaExplorer.length,n);
assert.equal(offers.policy.ewivaEnelEmspCommercialSeparation,true);
assert.equal(offers.policy.ewivaDirectContactlessRequiresStationCapabilityEvidence,true);
assert.ok(ewivaEmsp.every(o=>o.metadata?.rankableAsCpoDirect===false));
assert.ok([...ewivaEmsp,...ewivaSuper,...ewivaExplorer].every(o=>o.pricing?.priceSelectionBasis==='session_start_local_time'));
assert.ok(ewivaSuper.every(o=>o.monthlyFeeEur===4));
assert.ok(ewivaExplorer.every(o=>o.monthlyFeeEur===12));
assert.ok(!offers.directOffers.some(o=>o.provider==='Ewiva'));
const eid=ewivaEmsp.find(o=>o.metadata?.tariffClass==='HPC')?.evseIds?.[0];
assert.ok(eid);
const basic=ewivaEmsp.find(o=>o.evseIds?.[0]===eid), sup=ewivaSuper.find(o=>o.evseIds?.[0]===eid), exp=ewivaExplorer.find(o=>o.evseIds?.[0]===eid);
const rules=Direct.normalizePayload({country:'IT',emspOffers:[basic],subscriptionOffers:[sup,exp]}).offerRules;
const station={id:'IT:ewiva:test',countryCode:'IT',offers:rules};
let r=Session.evaluateStation(station,{energyKwh:20,durationMinutes:30,consumptionKwhPer100Km:15,targetCurrency:'EUR',startAt:'2026-08-31T19:05:00Z'},{selectedSubscriptions:[]});
assert.equal(r.best.provider,'Enel On Your Way');
r=Session.evaluateStation(station,{energyKwh:20,durationMinutes:30,consumptionKwhPer100Km:15,targetCurrency:'EUR',startAt:'2026-08-31T19:05:00Z'},{selectedSubscriptions:['enel_plug_and_go_super']});
assert.equal(r.best.subscriptionId,'enel_plug_and_go_super');
r=Session.evaluateStation(station,{energyKwh:20,durationMinutes:30,consumptionKwhPer100Km:15,targetCurrency:'EUR',startAt:'2026-08-31T19:05:00Z'},{selectedSubscriptions:['enel_plug_and_go_explorer']});
assert.equal(r.best.subscriptionId,'enel_plug_and_go_explorer');
console.log(JSON.stringify({ok:true,ewiva:n},null,2));
