const fs=require('fs');
const assert=require('assert');
const Engine=require('../assets/v9/device-scenario-engine.js');
const pack=JSON.parse(fs.readFileSync('data/v9/first-device-scenarios.json','utf8'));
const validation=Engine.validatePack(pack);
assert.equal(validation.valid,true,validation.errors.join(','));
assert.equal(validation.scenarioCount,10);
const countries=new Set(pack.scenarios.map(s=>s.countryCode));
assert(countries.has('FR')&&countries.has('NL')&&countries.has('IT'));
assert(pack.scenarios.some(s=>Number.isFinite(Number(s.disconnectOffsetMinutes))));
assert(pack.scenarios.some(s=>Array.isArray(s.selectedSubscriptions)&&s.selectedSubscriptions.length>0));
assert(pack.scenarios.some(s=>s.sortBy==='finalCost'));
assert(pack.scenarios.some(s=>s.sortBy==='totalTime'));
assert(pack.scenarios.some(s=>s.sortBy==='distance'));
const session=Engine.buildSession(pack.scenarios.find(s=>s.disconnectOffsetMinutes),new Date('2026-08-31T12:00:00Z'));
assert(session.disconnectAt);
const okArea={stations:[{id:'a'}],rankedStations:[{id:'a'}],diagnostics:{routingErrorCount:0,errors:[],fullyScoredStationCount:1,routingRequestedCount:1,routedStationCount:1}};
const ok=Engine.evaluateArea(pack.scenarios[0],okArea,1000);
assert.equal(ok.ok,true);
const pass=Engine.summary(Array.from({length:10},(_,i)=>({...ok,scenarioId:String(i)})));
assert.equal(pass.decision,'PASS');
const bad={...ok,ok:false,sourceErrors:1,reasons:['source_errors']};
const rollback=Engine.summary([...Array.from({length:9},(_,i)=>({...ok,scenarioId:String(i)})),bad]);
assert.equal(rollback.decision,'ROLLBACK');
console.log('first-device scenario pack OK');
