'use strict';
const assert=require('node:assert/strict');
const engine=require('../v9-production-runtime/assets/v9/pricing-engine.js');
function near(actual,want,message){assert.ok(Math.abs(actual-want)<1e-6,message+': '+actual+' vs '+want);}
const base={scope:'allDay',start:'00:00',end:'24:00',pricePerKwh:0.5,congestionTimePerMinute:0.2,congestionStartSoc:80};
const offer={id:'electra-evse-example',pricing:{type:'rules',rules:[base]},currency:'EUR'};
const session={startAt:'2026-10-09T12:00:00Z',timeZone:'Europe/Paris',energyKwh:20,durationMinutes:60,chargingMinutes:60,arrivalSoc:70,targetSoc:90};
let r=engine.evaluateOffer(offer,session);
assert.equal(r.complete,true);
near(r.totalEur,16,'SOC crossing at midpoint adds 30 congestion minutes');
near(r.components.congestionTime.costEur,6,'congestion component');
r=engine.evaluateOffer(offer,{...session,targetSoc:80});
near(r.totalEur,10,'no surcharge up to SOC80');
r=engine.evaluateOffer(offer,{...session,includeCongestionFees:false});
near(r.totalEur,10,'toggle disables congestion');
r=engine.evaluateOffer(offer,{...session,includeCongestion:true,arrivalSoc:80,targetSoc:100});
near(r.totalEur,22,'SOC already at 80');
const bounded={...base,congestionTimePerMinute:0,ocpiCongestionDurationBands:[[300,7800,0.2]]};
r=engine.evaluateOffer({...offer,pricing:{type:'rules',rules:[bounded]}},{...session,arrivalSoc:80,targetSoc:100,durationMinutes:20,chargingMinutes:20});
near(r.totalEur,14,'five-minute explicit band starts before SOC80 fee is billed');
r=engine.evaluateOffer({...offer,pricing:{type:'rules',rules:[bounded]}},{...session,durationMinutes:60,chargingMinutes:60});
near(r.totalEur,16,'intersection of default SOC80 and explicit duration band');
r=engine.evaluateOffer(offer,{...session,arrivalSoc:null,targetSoc:null});
assert.equal(r.complete,false);
assert.equal(r.reason,'congestion_soc_context_unavailable');
r=engine.evaluateOffer(offer,{...session,chargeTimeline:[{offsetMinutes:0,durationMinutes:20,startSoc:70,endSoc:80},{offsetMinutes:20,durationMinutes:40,startSoc:80,endSoc:90}]});
near(r.totalEur,18,'timeline crossing governs SOC fee');
const powerRule={scope:'allDay',pricePerKwh:.35};
near(engine.evaluateOffer({id:'electroverse',pricing:{type:'rules',rules:[powerRule]}},session).totalEur,7,'non-congestion pricing unaffected');
console.log('PASS: SOC80, bounded duration, toggle, fail-closed, EVSE baseline');